apiVersion: apps/v1
kind: Deployment
metadata:
  name: graham-banano-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: graham-banano-server
  template:
    metadata:
      labels:
        app: graham-banano-server
    spec:
      containers:
      - name: graham-banano-server
        image: replaceme
        ports:
        - containerPort: 11337
          name: api
        command: ["/bin/bash", "-c"]
        args: ["cp /config/config.yaml .; python bot.py start_server -p ? -u http://pippin-nano.pippin:11338 -s \"exit scam simulator\""]
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "7"
          - name: POSTGRES_HOST
            value: postgres.kubegres
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: postgres_password
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: bot_token
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: graham-banano
                key: wallet_id
        volumeMounts:
        - name: conf
          mountPath: /config
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: graham-banano
          defaultMode: 0755
