apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bananobot-ingress
  namespace: graham-banano
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - bananobotapi.banano.cc
      secretName: bananobotapi-banano-cc-server-secret
  rules:
    - host: bananobotapi.banano.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bananobot
                port:
                  number: 11337
