apiVersion: apps/v1
kind: Deployment
metadata:
  name: graham-nano
  namespace: graham-nano
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: graham-nano
  template:
    metadata:
      labels:
        app: graham-nano
    spec:
      containers:
      - name: graham-nano
        image: replaceme
        ports:
        - containerPort: 11337
          name: api
        command: ["/bin/bash", "-c"]
        args: ["cp /config/config.yaml .; python bot.py -p ! -u http://pippin-nano.pippin:11338 -s \"!help\""]
        env:
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "6"
          - name: POSTGRES_HOST
            value: postgres.postgres
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: graham-nano
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: graham-nano
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graham-nano
                key: postgres_password
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: graham-nano
                key: bot_token
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: graham-nano
                key: wallet_id
        volumeMounts:
        - name: conf
          mountPath: /config
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: graham-nano
          defaultMode: 0755
